<a href="https://colab.research.google.com/github/Dharshini1701/priyadharshini/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
m=[10,20,30,40]
s=pd.Series(m)
print(s)
print(type(s))


0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
details = {
"Name": ["Daniel", "Abhi", "Veeru", "Raju", "Kiran",
"Kedar", "Reena", "Karthik", "Satish"],
"Age": [20, 21, 23, 24, 25, 26, 27, 28, 29]
}
df = pd.DataFrame(details)
print(df)

      Name  Age
0   Daniel   20
1     Abhi   21
2    Veeru   23
3     Raju   24
4    Kiran   25
5    Kedar   26
6    Reena   27
7  Karthik   28
8   Satish   29


In [ ]:
import pandas as pd
p=['a','b','c','d']
s=pd.Series(p)
print(s)
print(type(s))

0    a
1    b
2    c
3    d
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
m=[10,20,30,40,50]
s=pd.Series(m,name="marks")
print(s)

0    10
1    20
2    30
3    40
4    50
Name: marks, dtype: int64


In [ ]:
import pandas as pd
l=['poi','plk','pou',]
s=pd.Series(l,name='student')
print(s)

0    poi
1    plk
2    pou
Name: student, dtype: object


In [ ]:
import pandas as pd
r=range(100)
a=list(r)
s=pd.Series(a)
print(s)

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int64


In [ ]:
import numpy as np
v=[10,20,30,40]
d=np.array(v)
print(d)
print(type(d))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd
import numpy as np
p=[10,20,30,40]
s=np.array(p)
print(s)
v=pd.Series(p)
print(v)

[10 20 30 40]
0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
import pandas as pd
m=[10,20,30,40]
s=pd.Series(m,index=[1,2,3,4,])
print(s)

1    10
2    20
3    30
4    40
dtype: int64


In [ ]:
import pandas as pd
k=[10,20,39,40]
i=['a','b','c','d']
s=pd.Series(k,index=i)
print(s)

a    10
b    20
c    39
d    40
dtype: int64


In [ ]:
import pandas as pd
prices=[100,300,500,600]
product=['mobile','lap','earbuds','headset']
s=pd.Series(prices,index=product)
print(s)

mobile     100
lap        300
earbuds    500
headset    600
dtype: int64


In [ ]:
import pandas as pd
n=[10,20,30,40]
s=pd.Series(n)
print(s)
print()
print(n[0])
print(n[3])

0    10
1    20
2    30
3    40
dtype: int64

10
40


In [ ]:
import pandas as pd
n=[10,20,30,40,59,np.nan]
s=pd.Series(n)
print(s)

0    10.0
1    20.0
2    30.0
3    40.0
4    59.0
5     NaN
dtype: float64


In [ ]:
import numpy as np
s=[10,20,np.nan,40]
d=pd.Series(s)
print(d)

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64


In [ ]:
import pandas as pd
o=['poi','oiu','tyu',np.nan]
s=pd.Series(o,name='student')
print(s)


0    poi
1    oiu
2    tyu
3    NaN
Name: student, dtype: object


In [ ]:
import pandas as pd
p=[10,20,30,40,50]
s=pd.Series(p)
print(s)
print()
print(s.values)

0    10
1    20
2    30
3    40
4    50
dtype: int64

[10 20 30 40 50]


In [ ]:
import pandas as pd
p=['ert','tyu','tyr','kil']
s=pd.Series(p)
print(s)
print()
print(s.index)

0    ert
1    tyu
2    tyr
3    kil
dtype: object

RangeIndex(start=0, stop=4, step=1)


In [ ]:
import pandas as pd
i=[10,20,30,40]
s=pd.Series(i)
print(s)
print()
print(s.size)

0    10
1    20
2    30
3    40
dtype: int64

4


In [ ]:
import pandas as pd
u=[110,20,30,40,50]
i=[1,2,3,4,5]
s=pd.Series(u,index=i)
print(s)
print(s.index)

1    110
2     20
3     30
4     40
5     50
dtype: int64
Index([1, 2, 3, 4, 5], dtype='int64')


In [ ]:
import pandas as pd
marks=[10,30,50,70]
i=['a','b','c','d']
s=pd.Series(marks,index=i)
print(s)
print(s.dtype)

a    10
b    30
c    50
d    70
dtype: int64
int64


In [ ]:
import pandas as pd
salaries=[100.0,2897.0,567.0]
s=pd.Series(salaries)
print(s)
print(s.dtype)

0     100.0
1    2897.0
2     567.0
dtype: float64
float64


In [ ]:
import pandas as pd
m=[10,30,40,50,60,70,89,90]
s=pd.Series(m)
print(s)
print(s.head())

0    10
1    30
2    40
3    50
4    60
5    70
6    89
7    90
dtype: int64
0    10
1    30
2    40
3    50
4    60
dtype: int64


In [ ]:
import pandas as pd
m=[10,50,60,70,89,65,45,34,56]
s=pd.Series(m)
print(s)
print(s.tail())

0    10
1    50
2    60
3    70
4    89
5    65
6    45
7    34
8    56
dtype: int64
4    89
5    65
6    45
7    34
8    56
dtype: int64


In [ ]:
import pandas as pd
p=[12,3,4,56,67,78]
s=pd.Series(p)
print(s)
print(s.sum())

0    12
1     3
2     4
3    56
4    67
5    78
dtype: int64
220


In [ ]:
import pandas as pd
w=[10,334,56,89,90]
s=pd.Series(w)
print(s)
print(s.count())

0     10
1    334
2     56
3     89
4     90
dtype: int64
5


In [ ]:
import pandas as pd
u=[45,67,89,99,34,56]
s=pd.Series(u)
print(s)
print(s.describe())

0    45
1    67
2    89
3    99
4    34
5    56
dtype: int64
count     6.000000
mean     65.000000
std      25.211109
min      34.000000
25%      47.750000
50%      61.500000
75%      83.500000
max      99.000000
dtype: float64


In [ ]:
import pandas as pd
e=[10,30,40,50,60,78]
s=pd.Series(e)
print(s)
print(s.unique())

0    10
1    30
2    40
3    50
4    60
5    78
dtype: int64
[10 30 40 50 60 78]


In [ ]:
import pandas as pd
v=[10,20,30,40,57]
s=pd.Series(v)
print(s)
print(s.nunique())

0    10
1    20
2    30
3    40
4    57
dtype: int64
5


In [ ]:
import pandas as pd
u=[12,34,56,78,90]
a=pd.Series(u)
print(a)
print(a.mean())

0    12
1    34
2    56
3    78
4    90
dtype: int64
54.0


In [ ]:
import pandas as pd
u=[12,34,56,78,9,90]
d=pd.DataFrame(u)
print(d)

    0
0  12
1  34
2  56
3  78
4   9
5  90


In [ ]:
import pandas as pd
u=[['poi',12],['ert',34],['wer',23]]
c='name','age'
d=pd.DataFrame(u,columns=c)
print(d)

  name  age
0  poi   12
1  ert   34
2  wer   23


In [ ]:
import pandas as pd
u={
    "Name":['daniel','pui','tyur'],
     "Age":[23,45,67]
    }
d=pd.DataFrame(u)
print(d)


     Name  Age
0  daniel   23
1     pui   45
2    tyur   67


In [ ]:
import pandas as pd
d=pd.read_csv("sales1.csv")
print(d)

    Order ID\tCustomer Name\tProduct\tQuantity
0     166837\tVeeru\t34in Ultrawide Monitor\t2
1                166838\tTarun\tSamsung m10\t3
2               166839\tKedar\t20in Monitor\t1
3                166840\tLavanya\tiPhone 11\t3
4          166841\tVenu\tMacbook Pro Laptop\t2
..                                         ...
595      167403\tBalaji\tMacbook Pro Laptop\t1
596        167404\tLavanya\tThinkPad Laptop\t1
597             167405\tVenu\tFlatscreen TV\t1
598             167406\tSiddhu\tSamsung m20\t2
599       167407\tTarun\tLG Washing Machine\t1

[600 rows x 1 columns]


In [ ]:
import pandas as pd
df = pd.read_csv("sales1.csv")
print(df.shape)

(600, 1)


In [ ]:
import pandas as pd
df = pd.read_csv("sales1.csv")
print(df.shape[0])

600


In [ ]:
import pandas as pd
a=pd.read_csv("sales5.csv")
print(a)

    Order_Id  Customer_Id              Mail_Id        Product_Name  \
0          1            1  nirekshan@gmail.com             Samsung   
1          2            2      kedar@gmail.com            iPhone 8   
2          3            3     Daniel@gmail.com  Kindle Paper White   
3          4            4     prasad@gmail.com          hTC mobile   
4          5            1  nirekshan@gmail.com             Samsung   
5          6            5     partha@gmail.com            iPhone 9   
6          7            4     prasad@gmail.com          hTC mobile   
7          8            6     shahid@gmail.com                iPad   
8          9            4     prasad@gmail.com  LG Washing Machine   
9         10            2      kedar@gmail.com            iPhone 8   
10        11            3     Daniel@gmail.com  Kindle Paper White   
11        12            3     Daniel@gmail.com            Sofa set   
12        13            2      kedar@gmail.com            iPhone 8   
13        14        

In [ ]:
import pandas as pd
a=pd.read_csv("sales3.csv")
d={"ord id":"ordered_id","cust name":"customer_name"}
print(a.head())
print()
a.rename(columns=d,inplace=True)
print(a.head())

   ord id cust name  cust id                   prod name  prod cost
0  192837     Veeru        3                   LG Mobile      65999
1  192838   Neelima       19        Apple iPad 10.2-inch      63000
2  192839    Balaji       12      34in Ultrawide Monitor      75999
3  192840    Shahid       20                   iPhone 11      60000
4  192841     Vinay       10  Bose SoundSport Headphones      69999

   ordered_id customer_name  cust id                   prod name  prod cost
0      192837         Veeru        3                   LG Mobile      65999
1      192838       Neelima       19        Apple iPad 10.2-inch      63000
2      192839        Balaji       12      34in Ultrawide Monitor      75999
3      192840        Shahid       20                   iPhone 11      60000
4      192841         Vinay       10  Bose SoundSport Headphones      69999


In [ ]:
import pandas as pd
a=pd.read_csv("sales1.csv")
print(a)

FileNotFoundError: [Errno 2] No such file or directory: 'sales1.csv'